/**
 * Dataset real de teste pra automação SNOW (snowAutomation.ts) — extraído direto de
 * VSR-05-07_Novo_Excel.xlsx (turbina VSR05-07, pás 410/413/414), mesmo layout de saída
 * do SNOW Processor. As 5 linhas "Blank Image" do fim da planilha original foram
 * OMITIDAS aqui de propósito (readDamageRows já as filtra em runtime — não são danos
 * reais, ver comentário em snowAutomation.ts).
 *
 * Uso: alimentar um dry-run do DamageEntryFiller sem precisar reabrir a planilha.
 */
import type { DamageReportRow } from '../snowAutomation'

export const vsr0507DamageRows: DamageReportRow[] = [
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Foreign Object',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nForeign Object',
    dfDistanceStart: 59.0,
    dfDistanceEnd: 59.1,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 80.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/1adb643a-31fb-443f-a2f1-ee5e8213e03a.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Air Inclusion',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nBubbles',
    dfDistanceStart: 59.0,
    dfDistanceEnd: 59.0,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 10.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/7c106d01-d348-4209-b6cb-4df7e45917d4.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Air Inclusion',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nBubbles',
    dfDistanceStart: 47.2,
    dfDistanceEnd: 47.9,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shell',
    bladeArea: 'PS',
    sizeMm: 700.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/5149911f-4a31-4168-bd96-ac4ff92906bc.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 40.5,
    dfDistanceEnd: 40.5,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shell',
    bladeArea: 'PS',
    sizeMm: 10.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/3719221c-55fd-4ded-b9fe-7ab1f74541c6.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Air Inclusion',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nBubbles',
    dfDistanceStart: 32.0,
    dfDistanceEnd: 32.1,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shell',
    bladeArea: 'PS',
    sizeMm: 120.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/a144734b-807a-40da-95eb-42e2e2aa7b25.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 55.1,
    dfDistanceEnd: 55.2,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 50.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/e4fab91b-c647-46d9-98b9-c4bcefd2cdc7.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 39.7,
    dfDistanceEnd: 39.8,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 50.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/567c959d-5abe-4a29-b02a-5cdc50758426.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 34.7,
    dfDistanceEnd: 35.0,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 250.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/f527e6f5-f1e6-44b5-9939-c6b53ce02ee3.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Air Inclusion',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nBubbles',
    dfDistanceStart: 34.7,
    dfDistanceEnd: 35.0,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 250.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/f1a74470-2bd4-4702-8a7f-162c6f24a84e.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Foreign Object',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nForeign Object',
    dfDistanceStart: 58.5,
    dfDistanceEnd: 59.0,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shell',
    bladeArea: 'PS',
    sizeMm: 500.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/6531c576-3e30-4e07-aad7-48a3362e9d0c.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Web Laminate',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 57.8,
    dfDistanceEnd: 57.8,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shear Web',
    bladeArea: 'Shear Web B',
    sizeMm: 30.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/9ba81ff3-ebdd-4afc-99f3-410ff4f947cb.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 44.5,
    dfDistanceEnd: 44.5,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 10.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/46001620-332e-4a5a-bb2b-803e33bf3aa7.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Web Laminate',
    failureType: 'Type of Failure is Missing',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nDamaged Laminate',
    dfDistanceStart: 37.6,
    dfDistanceEnd: 37.6,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shear Web',
    bladeArea: 'Shear Web B',
    sizeMm: 35.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/c9510183-d154-42fe-8430-5f2905d3c142.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 56.2,
    dfDistanceEnd: 56.4,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 200.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/33127edb-496e-4d7b-b58d-d9c0e2d53ad8.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 52.9,
    dfDistanceEnd: 52.9,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 20.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/66d472af-8235-42ee-9bf3-96dea6bf5add.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Web Laminate',
    failureType: 'Type of Failure is Missing',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nBonding Paste Failure',
    dfDistanceStart: 50.2,
    dfDistanceEnd: 50.3,
    profileDepthStart: 30,
    profileDepthEnd: 30,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shear Web',
    bladeArea: 'Shear Web A',
    sizeMm: 50.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/5db25684-ca6f-4c31-aa28-1faa0278edb6.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 49.8,
    dfDistanceEnd: 49.8,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 50.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/a88f3c09-097a-44c7-9ef5-f0ed18c67580.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 49.8,
    dfDistanceEnd: 49.8,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 10.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/adf5d33f-7885-4116-a75b-03f3a39396c5.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 47.8,
    dfDistanceEnd: 48.0,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 200.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/a646b0e1-46cd-4512-97ec-f35ba6378859.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Web Laminate',
    failureType: 'Type of Failure is Missing',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nDamaged Laminate',
    dfDistanceStart: 44.3,
    dfDistanceEnd: 44.4,
    profileDepthStart: 30,
    profileDepthEnd: 30,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shear Web',
    bladeArea: 'Shear Web A',
    sizeMm: 60.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/ecadc80f-eaed-459d-b173-3df9b9b07f60.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 43.7,
    dfDistanceEnd: 43.7,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 10.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/50075839-ce38-4851-9a63-6ceaa1aec285.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 39.4,
    dfDistanceEnd: 39.4,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 10.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/7fd52c43-1813-4734-8a59-5352e5b58c67.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 36.0,
    dfDistanceEnd: 36.6,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 600.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/0eb78e0c-a76f-4f8c-8f80-4dc2c945de12.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Web Laminate',
    failureType: 'Type of Failure is Missing',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nSemi Dry Glass',
    dfDistanceStart: 34.5,
    dfDistanceEnd: 34.6,
    profileDepthStart: 30,
    profileDepthEnd: 30,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shear Web',
    bladeArea: 'Shear Web A',
    sizeMm: 100.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/0c0ed4b5-cbcd-4e2d-a857-73382407e2d4.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Web Laminate',
    failureType: 'Type of Failure is Missing',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nBonding Paste Failure',
    dfDistanceStart: 31.4,
    dfDistanceEnd: 31.5,
    profileDepthStart: 30,
    profileDepthEnd: 30,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shear Web',
    bladeArea: 'Shear Web A',
    sizeMm: 100.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/03e22239-8c5a-4be7-a6c9-72792d8bbe4b.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 34.7,
    dfDistanceEnd: 35.2,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 500.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/0e3cd93e-270e-4650-89c4-f049f8d5ea03.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Air Inclusion',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nBubbles',
    dfDistanceStart: 40.1,
    dfDistanceEnd: 40.2,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 100.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/be5005ae-3215-4811-8ea8-c1a93eb18beb.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Type of Failure is Missing',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nSemi Dry Glass',
    dfDistanceStart: 43.6,
    dfDistanceEnd: 44.3,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 650.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/5909c7cb-1ebb-45bf-915e-8876ee7fa613.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Air Inclusion',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nBubbles',
    dfDistanceStart: 59.2,
    dfDistanceEnd: 59.2,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shell',
    bladeArea: 'PS',
    sizeMm: 20.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/1adc2eda-e471-4742-bd2b-2d25fb2c9a0c.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Foreign Object',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nForeign Object',
    dfDistanceStart: 40.4,
    dfDistanceEnd: 40.4,
    profileDepthStart: 55,
    profileDepthEnd: 55,
    insideOutside: 'Inside',
    bladeSection: 'Section 2',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 15.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/205bb28f-19eb-4db6-82e3-369fd1857cc1.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Web Laminate',
    failureType: 'Air Inclusion',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nBubbles',
    dfDistanceStart: 55.7,
    dfDistanceEnd: 55.8,
    profileDepthStart: 30,
    profileDepthEnd: 30,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shear Web',
    bladeArea: 'Shear Web A',
    sizeMm: 80.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/3a451e06-f6f4-49a0-9f98-b12493dfdafd.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 51.5,
    dfDistanceEnd: 51.5,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 10.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/b38a1125-aa4b-4f0b-b46e-a61fd9392d76.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 50.5,
    dfDistanceEnd: 50.5,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 10.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/11a0ced4-a2d2-4231-bc2f-395c570a65af.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 41.9,
    dfDistanceEnd: 42.0,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 70.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/213a2747-42f7-444a-b788-66362a2528db.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Web Laminate',
    failureType: 'Type of Failure is Missing',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nDamaged Laminate',
    dfDistanceStart: 38.2,
    dfDistanceEnd: 39.1,
    profileDepthStart: 30,
    profileDepthEnd: 30,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shear Web',
    bladeArea: 'Shear Web A',
    sizeMm: 850.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/0d191ebd-8be8-4fea-8f14-e1d7a767d611.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 33.6,
    dfDistanceEnd: 33.7,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 100.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/43b2c902-4fe5-4c95-b876-270cd02e8cc8.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 45.5,
    dfDistanceEnd: 45.5,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 15.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/dc511a9c-45a2-4313-b167-d683fb80ac7b.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 54.6,
    dfDistanceEnd: 54.6,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 10.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/f0ece44c-7158-4ca0-a532-cd19ff7b0c0c.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0413 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0413 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 52.9,
    dfDistanceEnd: 53.3,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 400.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/906ffdf9-9856-481e-bee5-d3630af10090.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 33.9,
    dfDistanceEnd: 33.9,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 50.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/793e9e60-f659-4b5d-89e5-ce917ae02082.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 47.2,
    dfDistanceEnd: 47.7,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 500.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/d2ba47ed-d52b-4766-9153-837bf52fb611.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0410 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0410 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 53.7,
    dfDistanceEnd: 53.9,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 200.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/ebaf6d18-f51e-42d1-ab52-e09533817d7d.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 32.5,
    dfDistanceEnd: 33.0,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 500.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/23ee37c0-2fc8-4bfc-99e5-333b438bc918.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 36.7,
    dfDistanceEnd: 36.8,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 50.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/cffb61b7-759c-47dd-85ae-170d22222c2b.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Deviation Core Material',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nStep',
    dfDistanceStart: 36.7,
    dfDistanceEnd: 36.7,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 15.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/2b9b587c-15e3-4a2d-bd0f-c8d508a42ea6.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Type of Failure is Missing',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nSemi Dry Glass',
    dfDistanceStart: 48.4,
    dfDistanceEnd: 50.0,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 1600.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/5426e292-bb02-44db-96b7-df7f49a24392.JPG',
    ],
  },
  {
    bladeSerialNumber: 'A1 811 0414 0115',
    excelRowIndex: 0,
    subComponent: 'Blade Inside - Shell',
    failureType: 'Delamination',
    damageDescription:
      'Inspection as per SN_241\nBlade: S/N0414 Set 0115\nInspection number: 1\nDelamination',
    dfDistanceStart: 50.4,
    dfDistanceEnd: 50.4,
    profileDepthStart: 10,
    profileDepthEnd: 10,
    insideOutside: 'Inside',
    bladeSection: 'Section 1',
    bladeSubSection: 'Shell',
    bladeArea: 'SS',
    sizeMm: 50.0,
    amountOfFindings: 1,
    photoUrls: [
      'https://blob.arthnex.com/galleries/5dc9bd7c-5e92-4b85-a3dc-3d2f65f3e15b.JPG',
    ],
  },
]
